Repository OpenSPP/openspp-modules, pull requests merged in 2023-12, with the labels that each got.

#272 initital commit spp_pmt
  setup/spp_pmt/odoo/addons/spp_pmt
  setup/spp_pmt/setup.py
  spp_pmt/README.rst
  spp_pmt/__init__.py
  spp_pmt/__manifest__.py
  spp_pmt/models/__init__.py
  spp_pmt/models/custom_fields_ui.py
  spp_pmt/models/pmt.py
  spp_pmt/security/ir.model.access.csv
  spp_pmt/static/description/icon.png
  spp_pmt/static/description/index.html
  spp_pmt/views/custom_fields_ui_view.xml
  spp_pmt/views/custom_registrant_view.xml
Labels: lgtm

#274 [UPD] add unique_id to service point and area
  spp_idpass/views/id_pass_view.xml
  spp_registrant_import/__init__.py
  spp_registrant_import/__manifest__.py
  spp_registrant_import/models/__init__.py
  spp_registrant_import/models/res_partner.py
  spp_registrant_import/models/spp_area.py
  spp_registrant_import/models/spp_service_point.py
  spp_registrant_import/tests/__init__.py
  spp_registrant_import/tests/test_area.py
  spp_registrant_import/tests/test_registrant.py
  spp_registrant_import/tests/test_service_point.py
  spp_registrant_import/views/res_partner_views.xml
  spp_registrant_import/views/spp_area_views.xml
  spp_registrant_import/views/spp_service_point_views.xml
Labels: lgtm, size:L

#282 improved crvs_data_source.xml, removed create_data_source function, f…
  spp_import_dci_api/data/crvs_data_source.xml
  spp_import_dci_api/models/fetch_crvs_beneficiary.py
  spp_registry_data_source/models/data_source.py
Labels: lgtm, size:M
