Repository OpenSPP/openspp-modules, pull requests merged in 2024-01, with the labels that each got.

#284 hide result of domain
  spp_import_dci_api/__manifest__.py
  spp_import_dci_api/static/src/js/field_domain.js
  spp_import_dci_api/views/fetch_crvs_beneficiary_views.xml
Labels: lgtm, size:S

#285 Module spp audit log
  spp_audit_config/__init__.py
  spp_audit_config/__manifest__.py
  spp_audit_config/data/audit_rule_data.xml
  spp_audit_config/models/__init__.py
  spp_audit_config/models/spp_audit_rule.py
  spp_audit_log/__manifest__.py
  spp_audit_log/models/__init__.py
  spp_audit_log/models/group.py
  spp_audit_log/models/spp_audit_log.py
  spp_audit_log/models/spp_audit_rule.py
  spp_audit_log/views/spp_audit_rule_views.xml
  spp_audit_post/models/spp_audit_log.py
  spp_audit_post/models/spp_audit_rule.py
  spp_audit_post/views/spp_audit_rule_views.xml
  spp_service_points/models/registrant.py
  spp_service_points/views/service_points_view.xml
Labels: lgtm, size:L

#289 fix issue on birthdate query not working
  spp_dci_api_server/controllers/controllers.py
Labels: lgtm, size:XS

#301 Set the spp_api_field_alias_data.xml to noupdate=1
  .pre-commit-config.yaml
  spp_api_records/data/spp_api_field_alias_data.xml
Labels: lgtm, size:XS

#313 Farmer registry fix migration issues
  spp_area/models/area.py
  test-requirements.txt
Labels: size:M
