Repository OpenSPP/openspp-modules, pull requests merged in 2024-02, with the labels that each got.

#314 Migrate 17.1.1 change request
  spp_change_request/__manifest__.py
  spp_change_request/tests/common.py
  spp_change_request/tests/test_change_requests.py
  spp_change_request/views/change_request_view.xml
  spp_change_request/views/dms_file_view.xml
  spp_change_request/views/registrant_view.xml
  spp_change_request/wizard/confirm_user_assignment_view.xml
  spp_change_request_add_children_demo/models/change_request_add_children.py
  spp_change_request_add_children_demo/views/change_request_add_children_view.xml
  theme_openspp/__manifest__.py
  theme_openspp/models/base.py
  theme_openspp/models/ir_module_module.py
  theme_openspp/models/ir_ui_view.py
  theme_openspp/models/res_config_settings.py
  theme_openspp/views/ir_ui_menu.xml
  theme_openspp/views/res_config_settings_views.xml
Labels: size:L

#315 Migrate 17.1.1 modules
  spp_custom_fields_ui/views/custom_fields_ui.xml
  spp_pmt/views/custom_fields_ui_view.xml
  spp_pos/data/entitlement_product.xml
  spp_pos/static/src/view/action_button.xml
  spp_pos/static/src/view/popup_voucher.xml
  spp_pos/tests/test_g2p_entitlement.py
  spp_starter/tests/test_spp_starter.py
  spp_starter/wizards/spp_starter_views.xml
Labels: size:L

#318 Migrate 17 field view get
  spp_api/tests/test_spp_api_field_alias.py
  spp_api/tests/test_spp_api_namespace.py
  spp_change_request/__manifest__.py
  spp_consent/wizard/record_consent.py
  spp_custom_field/models/cus_partner.py
  spp_idqueue/__manifest__.py
  spp_idqueue/static/src/js/form_controller.js
  spp_programs/__manifest__.py
  spp_programs/static/src/js/domain_field.js
  spp_programs/static/src/js/hide_button.js
  spp_programs_compliance_criteria/__manifest__.py
  spp_programs_compliance_criteria/static/src/js/field_domain.js
  spp_scan_id_document/__manifest__.py
  spp_scan_id_document/static/src/js/registrant.js
  theme_openspp/__manifest__.py
  theme_openspp/models/res_config_settings.py
Labels: size:M

#319 Farmer registry update gis
  spp_farmer_registry_base/__manifest__.py
  spp_farmer_registry_demo/views/group_view.xml
Labels: lgtm, size:L

#320 create ir.ui.view for res.partner with geoengine type
  spp_farmer_registry_base/__manifest__.py
  spp_farmer_registry_base/views/res_partner.xml
  spp_farmer_registry_demo/views/group_view.xml
Labels: lgtm, size:M

#322 Farmer registry update gis
  spp_farmer_registry_base/models/__init__.py
  spp_farmer_registry_base/models/partner.py
  spp_farmer_registry_base/views/res_partner.xml
Labels: lgtm, size:M

#323 Fix change request migration odoo17
  spp_change_request/__manifest__.py
  spp_change_request/models/change_request.py
  spp_change_request/security/ir.model.access.csv
  spp_change_request/views/change_request_view.xml
  spp_change_request_add_children_demo/__manifest__.py
  spp_change_request_add_children_demo/views/change_request_add_children_view.xml
Labels: size:L

#324 generate demo data farmer registry
  spp_farmer_registry_demo/__manifest__.py
  spp_farmer_registry_demo/data/asset_type_data.xml
  spp_farmer_registry_demo/data/machinery_type_data.xml
  spp_farmer_registry_demo/models/__init__.py
  spp_farmer_registry_demo/models/generate_farmer_data.py
  spp_farmer_registry_demo/security/ir.model.access.csv
  spp_farmer_registry_demo/tools/__init__.py
  spp_farmer_registry_demo/tools/generate_polygon.py
  spp_farmer_registry_demo/tools/random_location_in_kenya.py
  spp_farmer_registry_demo/views/generate_farmer_data_view.xml
  spp_farmer_registry_demo/views/group_view.xml
Labels: lgtm, size:XL

#325 Add theme_openspp_muk backend theme that extends MuK theme
  theme_openspp_muk/README.rst
  theme_openspp_muk/__init__.py
  theme_openspp_muk/__manifest__.py
  theme_openspp_muk/models/__init__.py
  theme_openspp_muk/models/res_config_settings.py
  theme_openspp_muk/static/description/icon.png
  theme_openspp_muk/static/description/index.html
  theme_openspp_muk/static/src/scss/colors.scss
  theme_openspp_muk/static/src/scss/colors_dark.scss
  theme_openspp_muk/static/src/scss/colors_light.scss
  theme_openspp_muk/static/src/scss/navbar.scss
Labels: size:XL

#326 added farmer details in generation of farmer demo data
  spp_farmer_registry_demo/models/farmer.py
  spp_farmer_registry_demo/models/generate_farmer_data.py
Labels: lgtm, size:L

#292 89 fix area import
  scripts/sync_issue_to_odoo.py
  spp_area/__manifest__.py
  spp_area/data/queue_job_channel.xml
  spp_area/models/area.py
  spp_area/models/area_import.py
  spp_area/security/ir.model.access.csv
  spp_area/tests/__init__.py
  spp_area/tests/common.py
  spp_area/tests/irq_adminboundaries_tabulardata.xlsx
  spp_area/tests/pse_adminboundaries_tabulardata.xlsx
  spp_area/tests/test_area_import.py
  spp_area/tests/test_area_import_raw.py
  spp_area/views/area.xml
  spp_area/views/area_import_views.xml
  test-requirements.txt
Labels: lgtm, size:XXL

#330 Fix program management UIs for odoo17
  g2p_entitlement_cash/wizard/create_program_wizard.xml
  spp_entitlement_in_kind/wizard/create_program_wizard.xml
  spp_programs/wizard/create_program_wizard.xml
Labels: size:L

#331 Fix producs UI in in-kind entitlement wizard
  spp_entitlement_in_kind/wizard/create_program_wizard.xml
Labels: size:M

#329 area import migration to odoo17
  spp_area/__manifest__.py
  spp_area/data/queue_job_channel.xml
  spp_area/models/area.py
  spp_area/models/area_import.py
  spp_area/security/ir.model.access.csv
  spp_area/tests/__init__.py
  spp_area/tests/common.py
  spp_area/tests/irq_adminboundaries_tabulardata.xlsx
  spp_area/tests/pse_adminboundaries_tabulardata.xlsx
  spp_area/tests/test_area_import.py
  spp_area/tests/test_area_import_raw.py
  spp_area/views/area.xml
  spp_area/views/area_import_views.xml
Labels: lgtm, size:XL

#332 Fix issue with in-kind entitlement
  spp_entitlement_in_kind/__manifest__.py
  spp_programs/views/cycle_view.xml
Labels: size:S

#334 Farmer Registry Dashboard
  spp_farmer_registry_dashboard/README.rst
  spp_farmer_registry_dashboard/__init__.py
  spp_farmer_registry_dashboard/__manifest__.py
  spp_farmer_registry_dashboard/data/dashboards.xml
  spp_farmer_registry_dashboard/data/files/farmer_registry_dashboard.json
  spp_farmer_registry_dashboard/reports/__init__.py
  spp_farmer_registry_dashboard/reports/farmer_registry_report.py
  spp_farmer_registry_dashboard/reports/farmer_registry_report_views.xml
  spp_farmer_registry_dashboard/reports/farmer_with_without_training_report.py
  spp_farmer_registry_dashboard/security/ir.model.access.csv
  spp_farmer_registry_dashboard/views/main_view.xml
Labels: size:XL

#337 Dashboard farmer registry add components
  spp_farmer_registry_dashboard/reports/__init__.py
  spp_farmer_registry_dashboard/reports/farmer_farm_details_report.py
  spp_farmer_registry_dashboard/reports/farmer_registry_report_views.xml
  spp_farmer_registry_dashboard/reports/farmer_with_without_training_report.py
  spp_farmer_registry_dashboard/security/ir.model.access.csv
  spp_farmer_registry_dashboard/views/main_view.xml
Labels: size:L

#296 Fix the bug that is generating an error when programs are created
  spp_pmt/__manifest__.py
  spp_pmt/models/pmt.py
Labels: size:M
